// AUTO-GENERATED by scripts/gen-registry.mjs — do not edit by hand.
// Consistent flat-design exercise animations, one shared rig + palette.
// Every asset is original (owned by 75DaysLab): no third-party license, free commercial use.
// Style consistency is exact across the set (single rig) → styleScore 100.
import type { FC } from 'react'

import squatMale from '@/public/lottie/male/squat.json'
import squatFemale from '@/public/lottie/female/squat.json'
import wallPushupMale from '@/public/lottie/male/wall-pushup.json'
import wallPushupFemale from '@/public/lottie/female/wall-pushup.json'
import gluteBridgeMale from '@/public/lottie/male/glute-bridge.json'
import gluteBridgeFemale from '@/public/lottie/female/glute-bridge.json'
import birdDogMale from '@/public/lottie/male/bird-dog.json'
import birdDogFemale from '@/public/lottie/female/bird-dog.json'
import marchInPlaceMale from '@/public/lottie/male/march-in-place.json'
import marchInPlaceFemale from '@/public/lottie/female/march-in-place.json'
import sideStepsMale from '@/public/lottie/male/side-steps.json'
import sideStepsFemale from '@/public/lottie/female/side-steps.json'
import pushupMale from '@/public/lottie/male/pushup.json'
import pushupFemale from '@/public/lottie/female/pushup.json'
import walkingLungeMale from '@/public/lottie/male/walking-lunge.json'
import walkingLungeFemale from '@/public/lottie/female/walking-lunge.json'
import plankMale from '@/public/lottie/male/plank.json'
import plankFemale from '@/public/lottie/female/plank.json'
import stepUpMale from '@/public/lottie/male/step-up.json'
import stepUpFemale from '@/public/lottie/female/step-up.json'
import mountainClimbersMale from '@/public/lottie/male/mountain-climbers.json'
import mountainClimbersFemale from '@/public/lottie/female/mountain-climbers.json'
import fireHydrantMale from '@/public/lottie/male/fire-hydrant.json'
import fireHydrantFemale from '@/public/lottie/female/fire-hydrant.json'
import burpeeMale from '@/public/lottie/male/burpee.json'
import burpeeFemale from '@/public/lottie/female/burpee.json'
import jumpSquatMale from '@/public/lottie/male/jump-squat.json'
import jumpSquatFemale from '@/public/lottie/female/jump-squat.json'
import pikePushupMale from '@/public/lottie/male/pike-pushup.json'
import pikePushupFemale from '@/public/lottie/female/pike-pushup.json'
import highKneesMale from '@/public/lottie/male/high-knees.json'
import highKneesFemale from '@/public/lottie/female/high-knees.json'
import jumpLungeMale from '@/public/lottie/male/jump-lunge.json'
import jumpLungeFemale from '@/public/lottie/female/jump-lunge.json'
import bicycleCrunchMale from '@/public/lottie/male/bicycle-crunch.json'
import bicycleCrunchFemale from '@/public/lottie/female/bicycle-crunch.json'

export type ExerciseLevel = 'beginner' | 'intermediate' | 'advanced'
export type Gender = 'male' | 'female'
export type ExerciseFocus = 'full' | 'core' | 'upper' | 'lower' | 'cardio' | 'yoga'

export interface ExerciseLottie {
  /** unique key: `${slug}-${gender}` */
  id: string
  /** exercise slug, shared across genders */
  slug: string
  name: string
  level: ExerciseLevel
  focus: ExerciseFocus[]
  gender: Gender
  /** parsed Lottie JSON — pass straight to lottie-react's animationData */
  data: object
  /** public URL under public/lottie/<gender>/ (for fetch-based players) */
  file: string
  /** public URL under public/lottie/<level>/ (level-organized copy) */
  levelFile: string
  creator: string
  source: string
  license: string
  /** 0–100; all share one rig so consistency is exact */
  styleScore: number
}

export const EXERCISE_LOTTIES: ExerciseLottie[] = [
  {
    id: 'squat-male',
    slug: 'squat',
    name: "Squat",
    level: 'beginner',
    focus: ["lower","full"],
    gender: 'male',
    data: squatMale as unknown as object,
    file: '/lottie/male/squat.json',
    levelFile: '/lottie/beginner/squat-male.json',
    creator: '75DaysLab',
    source: 'Original asset — generated in-house (see scripts/gen-lottie.mjs)',
    license: 'Project-owned · free for unlimited commercial use',
    styleScore: 100,
  },
  {
    id: 'squat-female',
    slug: 'squat',
    name: "Squat",
    level: 'beginner',
    focus: ["lower","full"],
    gender: 'female',
    data: squatFemale as unknown as object,
    file: '/lottie/female/squat.json',
    levelFile: '/lottie/beginner/squat-female.json',
    creator: '75DaysLab',
    source: 'Original asset — generated in-house (see scripts/gen-lottie.mjs)',
    license: 'Project-owned · free for unlimited commercial use',
    styleScore: 100,
  },
  {
    id: 'wall-pushup-male',
    slug: 'wall-pushup',
    name: "Wall Push-up",
    level: 'beginner',
    focus: ["upper","full"],
    gender: 'male',
    data: wallPushupMale as unknown as object,
    file: '/lottie/male/wall-pushup.json',
    levelFile: '/lottie/beginner/wall-pushup-male.json',
    creator: '75DaysLab',
    source: 'Original asset — generated in-house (see scripts/gen-lottie.mjs)',
    license: 'Project-owned · free for unlimited commercial use',
    styleScore: 100,
  },
  {
    id: 'wall-pushup-female',
    slug: 'wall-pushup',
    name: "Wall Push-up",
    level: 'beginner',
    focus: ["upper","full"],
    gender: 'female',
    data: wallPushupFemale as unknown as object,
    file: '/lottie/female/wall-pushup.json',
    levelFile: '/lottie/beginner/wall-pushup-female.json',
    creator: '75DaysLab',
    source: 'Original asset — generated in-house (see scripts/gen-lottie.mjs)',
    license: 'Project-owned · free for unlimited commercial use',
    styleScore: 100,
  },
  {
    id: 'glute-bridge-male',
    slug: 'glute-bridge',
    name: "Glute Bridge",
    level: 'beginner',
    focus: ["lower","core"],
    gender: 'male',
    data: gluteBridgeMale as unknown as object,
    file: '/lottie/male/glute-bridge.json',
    levelFile: '/lottie/beginner/glute-bridge-male.json',
    creator: '75DaysLab',
    source: 'Original asset — generated in-house (see scripts/gen-lottie.mjs)',
    license: 'Project-owned · free for unlimited commercial use',
    styleScore: 100,
  },
  {
    id: 'glute-bridge-female',
    slug: 'glute-bridge',
    name: "Glute Bridge",
    level: 'beginner',
    focus: ["lower","core"],
    gender: 'female',
    data: gluteBridgeFemale as unknown as object,
    file: '/lottie/female/glute-bridge.json',
    levelFile: '/lottie/beginner/glute-bridge-female.json',
    creator: '75DaysLab',
    source: 'Original asset — generated in-house (see scripts/gen-lottie.mjs)',
    license: 'Project-owned · free for unlimited commercial use',
    styleScore: 100,
  },
  {
    id: 'bird-dog-male',
    slug: 'bird-dog',
    name: "Bird Dog",
    level: 'beginner',
    focus: ["core","full"],
    gender: 'male',
    data: birdDogMale as unknown as object,
    file: '/lottie/male/bird-dog.json',
    levelFile: '/lottie/beginner/bird-dog-male.json',
    creator: '75DaysLab',
    source: 'Original asset — generated in-house (see scripts/gen-lottie.mjs)',
    license: 'Project-owned · free for unlimited commercial use',
    styleScore: 100,
  },
  {
    id: 'bird-dog-female',
    slug: 'bird-dog',
    name: "Bird Dog",
    level: 'beginner',
    focus: ["core","full"],
    gender: 'female',
    data: birdDogFemale as unknown as object,
    file: '/lottie/female/bird-dog.json',
    levelFile: '/lottie/beginner/bird-dog-female.json',
    creator: '75DaysLab',
    source: 'Original asset — generated in-house (see scripts/gen-lottie.mjs)',
    license: 'Project-owned · free for unlimited commercial use',
    styleScore: 100,
  },
  {
    id: 'march-in-place-male',
    slug: 'march-in-place',
    name: "March in Place",
    level: 'beginner',
    focus: ["cardio","lower"],
    gender: 'male',
    data: marchInPlaceMale as unknown as object,
    file: '/lottie/male/march-in-place.json',
    levelFile: '/lottie/beginner/march-in-place-male.json',
    creator: '75DaysLab',
    source: 'Original asset — generated in-house (see scripts/gen-lottie.mjs)',
    license: 'Project-owned · free for unlimited commercial use',
    styleScore: 100,
  },
  {
    id: 'march-in-place-female',
    slug: 'march-in-place',
    name: "March in Place",
    level: 'beginner',
    focus: ["cardio","lower"],
    gender: 'female',
    data: marchInPlaceFemale as unknown as object,
    file: '/lottie/female/march-in-place.json',
    levelFile: '/lottie/beginner/march-in-place-female.json',
    creator: '75DaysLab',
    source: 'Original asset — generated in-house (see scripts/gen-lottie.mjs)',
    license: 'Project-owned · free for unlimited commercial use',
    styleScore: 100,
  },
  {
    id: 'side-steps-male',
    slug: 'side-steps',
    name: "Side Steps",
    level: 'beginner',
    focus: ["cardio","lower"],
    gender: 'male',
    data: sideStepsMale as unknown as object,
    file: '/lottie/male/side-steps.json',
    levelFile: '/lottie/beginner/side-steps-male.json',
    creator: '75DaysLab',
    source: 'Original asset — generated in-house (see scripts/gen-lottie.mjs)',
    license: 'Project-owned · free for unlimited commercial use',
    styleScore: 100,
  },
  {
    id: 'side-steps-female',
    slug: 'side-steps',
    name: "Side Steps",
    level: 'beginner',
    focus: ["cardio","lower"],
    gender: 'female',
    data: sideStepsFemale as unknown as object,
    file: '/lottie/female/side-steps.json',
    levelFile: '/lottie/beginner/side-steps-female.json',
    creator: '75DaysLab',
    source: 'Original asset — generated in-house (see scripts/gen-lottie.mjs)',
    license: 'Project-owned · free for unlimited commercial use',
    styleScore: 100,
  },
  {
    id: 'pushup-male',
    slug: 'pushup',
    name: "Push-up",
    level: 'intermediate',
    focus: ["upper","core"],
    gender: 'male',
    data: pushupMale as unknown as object,
    file: '/lottie/male/pushup.json',
    levelFile: '/lottie/intermediate/pushup-male.json',
    creator: '75DaysLab',
    source: 'Original asset — generated in-house (see scripts/gen-lottie.mjs)',
    license: 'Project-owned · free for unlimited commercial use',
    styleScore: 100,
  },
  {
    id: 'pushup-female',
    slug: 'pushup',
    name: "Push-up",
    level: 'intermediate',
    focus: ["upper","core"],
    gender: 'female',
    data: pushupFemale as unknown as object,
    file: '/lottie/female/pushup.json',
    levelFile: '/lottie/intermediate/pushup-female.json',
    creator: '75DaysLab',
    source: 'Original asset — generated in-house (see scripts/gen-lottie.mjs)',
    license: 'Project-owned · free for unlimited commercial use',
    styleScore: 100,
  },
  {
    id: 'walking-lunge-male',
    slug: 'walking-lunge',
    name: "Walking Lunge",
    level: 'intermediate',
    focus: ["lower","full"],
    gender: 'male',
    data: walkingLungeMale as unknown as object,
    file: '/lottie/male/walking-lunge.json',
    levelFile: '/lottie/intermediate/walking-lunge-male.json',
    creator: '75DaysLab',
    source: 'Original asset — generated in-house (see scripts/gen-lottie.mjs)',
    license: 'Project-owned · free for unlimited commercial use',
    styleScore: 100,
  },
  {
    id: 'walking-lunge-female',
    slug: 'walking-lunge',
    name: "Walking Lunge",
    level: 'intermediate',
    focus: ["lower","full"],
    gender: 'female',
    data: walkingLungeFemale as unknown as object,
    file: '/lottie/female/walking-lunge.json',
    levelFile: '/lottie/intermediate/walking-lunge-female.json',
    creator: '75DaysLab',
    source: 'Original asset — generated in-house (see scripts/gen-lottie.mjs)',
    license: 'Project-owned · free for unlimited commercial use',
    styleScore: 100,
  },
  {
    id: 'plank-male',
    slug: 'plank',
    name: "Plank",
    level: 'intermediate',
    focus: ["core","full"],
    gender: 'male',
    data: plankMale as unknown as object,
    file: '/lottie/male/plank.json',
    levelFile: '/lottie/intermediate/plank-male.json',
    creator: '75DaysLab',
    source: 'Original asset — generated in-house (see scripts/gen-lottie.mjs)',
    license: 'Project-owned · free for unlimited commercial use',
    styleScore: 100,
  },
  {
    id: 'plank-female',
    slug: 'plank',
    name: "Plank",
    level: 'intermediate',
    focus: ["core","full"],
    gender: 'female',
    data: plankFemale as unknown as object,
    file: '/lottie/female/plank.json',
    levelFile: '/lottie/intermediate/plank-female.json',
    creator: '75DaysLab',
    source: 'Original asset — generated in-house (see scripts/gen-lottie.mjs)',
    license: 'Project-owned · free for unlimited commercial use',
    styleScore: 100,
  },
  {
    id: 'step-up-male',
    slug: 'step-up',
    name: "Step Up",
    level: 'intermediate',
    focus: ["lower","cardio"],
    gender: 'male',
    data: stepUpMale as unknown as object,
    file: '/lottie/male/step-up.json',
    levelFile: '/lottie/intermediate/step-up-male.json',
    creator: '75DaysLab',
    source: 'Original asset — generated in-house (see scripts/gen-lottie.mjs)',
    license: 'Project-owned · free for unlimited commercial use',
    styleScore: 100,
  },
  {
    id: 'step-up-female',
    slug: 'step-up',
    name: "Step Up",
    level: 'intermediate',
    focus: ["lower","cardio"],
    gender: 'female',
    data: stepUpFemale as unknown as object,
    file: '/lottie/female/step-up.json',
    levelFile: '/lottie/intermediate/step-up-female.json',
    creator: '75DaysLab',
    source: 'Original asset — generated in-house (see scripts/gen-lottie.mjs)',
    license: 'Project-owned · free for unlimited commercial use',
    styleScore: 100,
  },
  {
    id: 'mountain-climbers-male',
    slug: 'mountain-climbers',
    name: "Mountain Climbers",
    level: 'intermediate',
    focus: ["cardio","core"],
    gender: 'male',
    data: mountainClimbersMale as unknown as object,
    file: '/lottie/male/mountain-climbers.json',
    levelFile: '/lottie/intermediate/mountain-climbers-male.json',
    creator: '75DaysLab',
    source: 'Original asset — generated in-house (see scripts/gen-lottie.mjs)',
    license: 'Project-owned · free for unlimited commercial use',
    styleScore: 100,
  },
  {
    id: 'mountain-climbers-female',
    slug: 'mountain-climbers',
    name: "Mountain Climbers",
    level: 'intermediate',
    focus: ["cardio","core"],
    gender: 'female',
    data: mountainClimbersFemale as unknown as object,
    file: '/lottie/female/mountain-climbers.json',
    levelFile: '/lottie/intermediate/mountain-climbers-female.json',
    creator: '75DaysLab',
    source: 'Original asset — generated in-house (see scripts/gen-lottie.mjs)',
    license: 'Project-owned · free for unlimited commercial use',
    styleScore: 100,
  },
  {
    id: 'fire-hydrant-male',
    slug: 'fire-hydrant',
    name: "Fire Hydrant",
    level: 'intermediate',
    focus: ["lower","core"],
    gender: 'male',
    data: fireHydrantMale as unknown as object,
    file: '/lottie/male/fire-hydrant.json',
    levelFile: '/lottie/intermediate/fire-hydrant-male.json',
    creator: '75DaysLab',
    source: 'Original asset — generated in-house (see scripts/gen-lottie.mjs)',
    license: 'Project-owned · free for unlimited commercial use',
    styleScore: 100,
  },
  {
    id: 'fire-hydrant-female',
    slug: 'fire-hydrant',
    name: "Fire Hydrant",
    level: 'intermediate',
    focus: ["lower","core"],
    gender: 'female',
    data: fireHydrantFemale as unknown as object,
    file: '/lottie/female/fire-hydrant.json',
    levelFile: '/lottie/intermediate/fire-hydrant-female.json',
    creator: '75DaysLab',
    source: 'Original asset — generated in-house (see scripts/gen-lottie.mjs)',
    license: 'Project-owned · free for unlimited commercial use',
    styleScore: 100,
  },
  {
    id: 'burpee-male',
    slug: 'burpee',
    name: "Burpee",
    level: 'advanced',
    focus: ["full","cardio"],
    gender: 'male',
    data: burpeeMale as unknown as object,
    file: '/lottie/male/burpee.json',
    levelFile: '/lottie/advanced/burpee-male.json',
    creator: '75DaysLab',
    source: 'Original asset — generated in-house (see scripts/gen-lottie.mjs)',
    license: 'Project-owned · free for unlimited commercial use',
    styleScore: 100,
  },
  {
    id: 'burpee-female',
    slug: 'burpee',
    name: "Burpee",
    level: 'advanced',
    focus: ["full","cardio"],
    gender: 'female',
    data: burpeeFemale as unknown as object,
    file: '/lottie/female/burpee.json',
    levelFile: '/lottie/advanced/burpee-female.json',
    creator: '75DaysLab',
    source: 'Original asset — generated in-house (see scripts/gen-lottie.mjs)',
    license: 'Project-owned · free for unlimited commercial use',
    styleScore: 100,
  },
  {
    id: 'jump-squat-male',
    slug: 'jump-squat',
    name: "Jump Squat",
    level: 'advanced',
    focus: ["lower","cardio"],
    gender: 'male',
    data: jumpSquatMale as unknown as object,
    file: '/lottie/male/jump-squat.json',
    levelFile: '/lottie/advanced/jump-squat-male.json',
    creator: '75DaysLab',
    source: 'Original asset — generated in-house (see scripts/gen-lottie.mjs)',
    license: 'Project-owned · free for unlimited commercial use',
    styleScore: 100,
  },
  {
    id: 'jump-squat-female',
    slug: 'jump-squat',
    name: "Jump Squat",
    level: 'advanced',
    focus: ["lower","cardio"],
    gender: 'female',
    data: jumpSquatFemale as unknown as object,
    file: '/lottie/female/jump-squat.json',
    levelFile: '/lottie/advanced/jump-squat-female.json',
    creator: '75DaysLab',
    source: 'Original asset — generated in-house (see scripts/gen-lottie.mjs)',
    license: 'Project-owned · free for unlimited commercial use',
    styleScore: 100,
  },
  {
    id: 'pike-pushup-male',
    slug: 'pike-pushup',
    name: "Pike Push-up",
    level: 'advanced',
    focus: ["upper","core"],
    gender: 'male',
    data: pikePushupMale as unknown as object,
    file: '/lottie/male/pike-pushup.json',
    levelFile: '/lottie/advanced/pike-pushup-male.json',
    creator: '75DaysLab',
    source: 'Original asset — generated in-house (see scripts/gen-lottie.mjs)',
    license: 'Project-owned · free for unlimited commercial use',
    styleScore: 100,
  },
  {
    id: 'pike-pushup-female',
    slug: 'pike-pushup',
    name: "Pike Push-up",
    level: 'advanced',
    focus: ["upper","core"],
    gender: 'female',
    data: pikePushupFemale as unknown as object,
    file: '/lottie/female/pike-pushup.json',
    levelFile: '/lottie/advanced/pike-pushup-female.json',
    creator: '75DaysLab',
    source: 'Original asset — generated in-house (see scripts/gen-lottie.mjs)',
    license: 'Project-owned · free for unlimited commercial use',
    styleScore: 100,
  },
  {
    id: 'high-knees-male',
    slug: 'high-knees',
    name: "High Knees",
    level: 'advanced',
    focus: ["cardio","core"],
    gender: 'male',
    data: highKneesMale as unknown as object,
    file: '/lottie/male/high-knees.json',
    levelFile: '/lottie/advanced/high-knees-male.json',
    creator: '75DaysLab',
    source: 'Original asset — generated in-house (see scripts/gen-lottie.mjs)',
    license: 'Project-owned · free for unlimited commercial use',
    styleScore: 100,
  },
  {
    id: 'high-knees-female',
    slug: 'high-knees',
    name: "High Knees",
    level: 'advanced',
    focus: ["cardio","core"],
    gender: 'female',
    data: highKneesFemale as unknown as object,
    file: '/lottie/female/high-knees.json',
    levelFile: '/lottie/advanced/high-knees-female.json',
    creator: '75DaysLab',
    source: 'Original asset — generated in-house (see scripts/gen-lottie.mjs)',
    license: 'Project-owned · free for unlimited commercial use',
    styleScore: 100,
  },
  {
    id: 'jump-lunge-male',
    slug: 'jump-lunge',
    name: "Jump Lunge",
    level: 'advanced',
    focus: ["lower","cardio"],
    gender: 'male',
    data: jumpLungeMale as unknown as object,
    file: '/lottie/male/jump-lunge.json',
    levelFile: '/lottie/advanced/jump-lunge-male.json',
    creator: '75DaysLab',
    source: 'Original asset — generated in-house (see scripts/gen-lottie.mjs)',
    license: 'Project-owned · free for unlimited commercial use',
    styleScore: 100,
  },
  {
    id: 'jump-lunge-female',
    slug: 'jump-lunge',
    name: "Jump Lunge",
    level: 'advanced',
    focus: ["lower","cardio"],
    gender: 'female',
    data: jumpLungeFemale as unknown as object,
    file: '/lottie/female/jump-lunge.json',
    levelFile: '/lottie/advanced/jump-lunge-female.json',
    creator: '75DaysLab',
    source: 'Original asset — generated in-house (see scripts/gen-lottie.mjs)',
    license: 'Project-owned · free for unlimited commercial use',
    styleScore: 100,
  },
  {
    id: 'bicycle-crunch-male',
    slug: 'bicycle-crunch',
    name: "Bicycle Crunch",
    level: 'advanced',
    focus: ["core"],
    gender: 'male',
    data: bicycleCrunchMale as unknown as object,
    file: '/lottie/male/bicycle-crunch.json',
    levelFile: '/lottie/advanced/bicycle-crunch-male.json',
    creator: '75DaysLab',
    source: 'Original asset — generated in-house (see scripts/gen-lottie.mjs)',
    license: 'Project-owned · free for unlimited commercial use',
    styleScore: 100,
  },
  {
    id: 'bicycle-crunch-female',
    slug: 'bicycle-crunch',
    name: "Bicycle Crunch",
    level: 'advanced',
    focus: ["core"],
    gender: 'female',
    data: bicycleCrunchFemale as unknown as object,
    file: '/lottie/female/bicycle-crunch.json',
    levelFile: '/lottie/advanced/bicycle-crunch-female.json',
    creator: '75DaysLab',
    source: 'Original asset — generated in-house (see scripts/gen-lottie.mjs)',
    license: 'Project-owned · free for unlimited commercial use',
    styleScore: 100,
  },
]

export const byLevel = (level: ExerciseLevel): ExerciseLottie[] =>
  EXERCISE_LOTTIES.filter(e => e.level === level)

export const byGender = (gender: Gender): ExerciseLottie[] =>
  EXERCISE_LOTTIES.filter(e => e.gender === gender)

export const byFocus = (focus: ExerciseFocus): ExerciseLottie[] =>
  EXERCISE_LOTTIES.filter(e => e.focus.includes(focus))

export const bySlug = (slug: string): ExerciseLottie[] =>
  EXERCISE_LOTTIES.filter(e => e.slug === slug)

export const findExercise = (slug: string, gender: Gender): ExerciseLottie | undefined =>
  EXERCISE_LOTTIES.find(e => e.slug === slug && e.gender === gender)

/**
 * Ready-to-use lottie-react example:
 *
 *   import Lottie from 'lottie-react'
 *   import { findExercise } from '@/lib/fitness/exerciseLottieRegistry'
 *
 *   const squat = findExercise('squat', 'male')!
 *   <Lottie animationData={squat.data} loop autoplay style={{ width: 240 }} />
 */
export type ExerciseLottieComponent = FC<{ slug: string; gender?: Gender }>
